import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [item, setItems] = useState();

  useEffect(() => {
    fetch("https://weather.pmv-app.workers.dev/")
      .then((res) => res.json())
      .then((result) => {
        setItems(result);
      });
  }, []);

  return (
    <div className="container mx-auo text-center p-12 ">
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by Weather app" />
      </Head>
      <body>
        <main>
          <div>
            <h1 className="font-serif text-6xl font-extrabold border rounded-2xl p-4 border-green-900">
              Weather app
            </h1>
          </div>
          {item && (
            <div className="p-4 text-lime-900	">
              <p className="text-2xl font-bold">
                {" "}
                City : {item.name} , {item.sys.country}{" "}
              </p>
              <p className="text-2xl font-bold">
                {" "}
                Time : {new Date().toLocaleTimeString()}
              </p>
              <p className="text-2xl font-bold ">
                {" "}
                Temprature : {(item.main.temp - 273.15).toFixed(2)} C
              </p>
            </div>
          )}
        </main>
        <div>
          <footer className="mt-8 text-base text-gray-400 md:order-1 md:mt-0">
            &copy; 2022 Weather app, Inc. All rights reserved.
          </footer>
        </div>
      </body>
    </div>
  );
}
